In [7]:
#  test
import numpy as np

np.array([1,2,3])
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# 误差
误差是 $\varepsilon ^\left(i\right)$ 是独立并且具有相同的分布，并服从均值为0，方差为 $\theta$的高斯分布

独立：每个样本之间是独立的，没关系

同分布：具有相同的分布

高斯分布：

预测值与误差：$y^\left(i\right) = \theta^\left(T\right)x^\left(i\right) + \varepsilon ^\left(i\right)$ .....(1)

由于误差服从高斯分布：$p(\epsilon^\left(i\right)) = \frac {1}{\sqrt[]{2\pi} \sigma} exp(-\frac{(\varepsilon^\left(i\right))^2}{2\sigma^2})$ .....(2)

将2式代入1式子得：$p(y^\left(i\right)| x^\left(i\right);\theta) = \frac {1}{\sqrt[]{2\pi} \sigma} exp(-\frac{(y^\left(i\right) - \theta^T x^\left(i\right))^2}{2\sigma^2})$ .....(2)

### 似然函数：$L(\theta) = \prod_\left(i=1\right)^m p(y^\left(i\right)| x^\left(i\right);\theta)  = \prod_\left(i=1\right)^m \frac {1}{\sqrt[]{2\pi} \sigma} exp(-\frac{(\varepsilon^\left(i\right))^2}{2\sigma^2}) $ 

### 将似然函数转换成对数似然，将累乘变为累加

$ J(\theta) = 1/2 \sum_\left(i=1\right)^m (y^\left(i\right) - \theta^T x^\left(i\right))^2 = \frac {1}{2} (X\theta - y)^T(X\theta - y)）$

求偏导数 $ \nabla_\theta J(\theta) = X^TX\theta - X^Ty$

让偏导数等于0 : $\theta = (X^TX)^\left(-1\right) X^Ty$

# 评估方法

 最常用的评估项 $ R^2:1- \frac {\sum_\left(i=1\right)^m (y_i^\hat - y_i)^2}{\sum_\left(i=1\right)^m (y_i - \overline y)^2}$

R 取值越等于1，我们认为模型拟合越小

# 梯度下降

引入：当我们得到一个目标函数后，如何进行求解？

常规套路：机器学习的套路就是我交给机器一堆数据，然后告诉它什么样的学习方式是对的（目标函数），然后让他朝着这个方向去做

如何优化：一步步迭代


- 批量梯度下降：容易得到最优解，但是由于每次考虑所以样本，速度很慢

- 随机梯度下降：每次找一个样本，迭代速度快，但不一定每次都朝着收敛的方向

- 小批量梯度下降法：每次更新选择一小部分数据来算，实用！

### 学习率（步长）
- 对结果会产生巨大的影响，一般小一点 （0.01-更小）
- 如何选择：从小的
- 批处理数量：32，64，128... 综合考虑内存和效率

---

# 逻辑回归 （Logistics Regression）
- 经典的二分类的算法
- 机器学习算法选择，先逻辑回归再用复杂的，能简单的再用简单的
- 逻辑回归的决策边界，可以是非线性的

# Sigmod 函数
- 公式： $g(Z) = \frac {1}{1+e^\left(-z\right)}$
- 自变量取值为任意实数，值域 [0,1]
- 解释:将任意的输入映射到[0,1]区间，我们在线性回归中可以得到一个预测值，再将该值映射到Sigmond函数，这样就完成了从值到概率的转换