#  1 numpy 导入数据

In [8]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.txt",delimiter=',',dtype=str)
print(type(world_alcohol))
print(world_alcohol)
# print(help(np.genfromtxt))

<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [6]:
    vector = np.array([1,2,3,4])
    print(vector.shape)

(4,)


In [7]:
matrix = np.array([[5,10,15],[20,25,30]])
print(matrix.shape)

(2, 3)


In [9]:
numbers = np.array([1,2,3,4])
print(numbers.dtype)

int64


In [10]:
numbers2 = np.array([1,2,3,4.0])
print(numbers2.dtype)

float64


In [13]:
# 取数据
row14 = world_alcohol[2,4]
print(row14)
row22 = world_alcohol[2,2]
print(row22)

0.5
Uruguay


In [14]:
vector = np.array([1,2,3,4,5])
print(vector[1:3])

[2 3]


In [23]:
matrix = np.array([[1,2,3,4],
                          [2,3,4,5],
                          [4,5,6,7]])
# 取二行
print(matrix[1])
# 取第二列
print(matrix[:,1])

# 取第二行第二列
print(matrix[1,1])

# 取 1-2行，和1-3列
print(matrix[0:1,0:2])

[2 3 4 5]
[2 3 5]
3
[[1 2]]


In [29]:
# 判断运算
indexs = vector == 2
print(indexs)
indexs2 = matrix == 4
print(indexs2)

[False  True False False False]
[[False False False  True]
 [False False  True False]
 [ True False False False]]


In [30]:
# 使用索引数组取值
print(vector[indexs])

[2]


In [31]:
# 使用索引matrix取值
print(matrix[indexs2])

[4 4 4]


In [37]:
second_index = (matrix[:,1] == 3)
print(second_index)
print(matrix[second_index,:])

[False  True False]
[[2 3 4 5]]


In [39]:
vector = np.array([5,10,15,20])
# and
equal_to_ten_and_five = (vector ==10) &(vector == 5)
print(equal_to_ten_and_five)

[False False False False]


In [40]:
# 或
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


In [45]:
# 改变数据类型
vector = np.array(["1","2","3"])
print(vector)
print(vector.dtype)

vector = vector.astype(float)
print(vector)
print(vector.dtype)


['1' '2' '3']
<U1
[1. 2. 3.]
float64


# functions

In [46]:
# max min
min = min(vector)
print(min)

1.0


In [52]:
# max
maxnum = vector.max()
print(maxnum)

3.0


In [55]:
print(matrix)
# sum
# axis = 1  row
matrix.sum(axis=1)

[[1 2 3 4]
 [2 3 4 5]
 [4 5 6 7]]


array([10, 14, 22])

In [54]:
matrix.sum(axis=0) #axis=0-column

array([ 7, 10, 13, 16])

# arrange

In [69]:
# arrange
a = np.arange(15)
print(a)
b= np.arange(1,10,2)
print(b)
c = np.arange(0,2,0.3)
print('c = %s' % c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[1 3 5 7 9]
c = [0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [58]:
a = a.reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [59]:
print(a.shape)

(3, 5)


In [60]:
# 维度，二维矩阵
a.ndim

2

In [61]:
a.dtype.name

'int64'

In [62]:
a.size

15

In [64]:
# 创建一个空矩阵
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [65]:
#创建一个 元素全为1 的矩阵
np.ones((4,5),dtype=np.int64)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Random 随机函数

In [71]:
# 随机（2，3）矩阵，默认从 -1到1之间的值
np.random.random((2,3))

array([[0.28360794, 0.71965449, 0.78943771],
       [0.11503324, 0.49501073, 0.05230324]])

# Linespace

In [80]:
from numpy import pi
a = np.linspace(0,2*pi,20)
print(a)

[0.         0.33069396 0.66138793 0.99208189 1.32277585 1.65346982
 1.98416378 2.31485774 2.64555171 2.97624567 3.30693964 3.6376336
 3.96832756 4.29902153 4.62971549 4.96040945 5.29110342 5.62179738
 5.95249134 6.28318531]


In [83]:
# 求余弦函数 
np.sin(a)

array([ 0.00000000e+00,  3.24699469e-01,  6.14212713e-01,  8.37166478e-01,
        9.69400266e-01,  9.96584493e-01,  9.15773327e-01,  7.35723911e-01,
        4.75947393e-01,  1.64594590e-01, -1.64594590e-01, -4.75947393e-01,
       -7.35723911e-01, -9.15773327e-01, -9.96584493e-01, -9.69400266e-01,
       -8.37166478e-01, -6.14212713e-01, -3.24699469e-01, -2.44929360e-16])

# 基本运算

In [76]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a,b)

c = a-b
print(c)

[20 30 40 50] [0 1 2 3]
[20 29 38 47]


# 矩阵乘法

In [86]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print(A)
print('-------')
print(B)
print('-------')
# 每一项元素相乘
print(A*B)
print('-------')
# 矩阵乘
print(A.dot(B))


[[1 1]
 [0 1]]
-------
[[2 0]
 [3 4]]
-------
[[2 0]
 [0 4]]
-------
[[5 4]
 [3 4]]


In [88]:
a = np.floor(10*np.random.random((3,4)))
print(a)

[[0. 4. 2. 5.]
 [7. 4. 3. 3.]
 [9. 4. 2. 5.]]


In [89]:
# 矩阵牌匾成数组
a.ravel()

array([0., 4., 2., 5., 7., 4., 3., 3., 9., 4., 2., 5.])

In [90]:
# 转置
a.T

array([[0., 7., 9.],
       [4., 4., 4.],
       [2., 3., 2.],
       [5., 3., 5.]])

In [93]:
# reshape
a.reshape(4,3)

array([[0., 4., 2., 5.],
       [7., 4., 3., 3.],
       [9., 4., 2., 5.]])

# hstack 和 vstack

In [95]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print('-------')
print(b)

[[9. 2.]
 [2. 5.]]
-------
[[6. 4.]
 [5. 2.]]


In [102]:
# 增加数据 vstack
print(np.vstack((a,b)))

[[9. 2.]
 [2. 5.]
 [6. 4.]
 [5. 2.]]


In [100]:
# hstack 
# 增加特征
print(np.hstack((a,b)))

[[9. 2. 6. 4.]
 [2. 5. 5. 2.]]


# hsplit and vsplit

In [109]:
a = np.floor(10*np.random.random((2,12)))
b = np.floor(10*np.random.random((12,2)))
print(a)
print('-------')
print(b)

[[6. 1. 1. 0. 4. 8. 6. 1. 3. 0. 8. 8.]
 [7. 2. 4. 9. 9. 4. 1. 0. 3. 9. 6. 3.]]
-------
[[4. 0.]
 [0. 3.]
 [6. 5.]
 [0. 5.]
 [7. 9.]
 [2. 9.]
 [9. 5.]
 [7. 0.]
 [0. 9.]
 [6. 7.]
 [6. 6.]
 [5. 3.]]


In [114]:
# hsplit
print(np.hsplit(a,3))

[array([[6., 1., 1., 0.],
       [7., 2., 4., 9.]]), array([[4., 8., 6., 1.],
       [9., 4., 1., 0.]]), array([[3., 0., 8., 8.],
       [3., 9., 6., 3.]])]


In [112]:
# vsplit
np.vsplit(b,3)

[array([[4., 0.],
        [0., 3.],
        [6., 5.],
        [0., 5.]]), array([[7., 9.],
        [2., 9.],
        [9., 5.],
        [7., 0.]]), array([[0., 9.],
        [6., 7.],
        [6., 6.],
        [5., 3.]])]

---

# 浅复制

In [130]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [125]:
b = a

In [126]:
print(a is b)

True


In [127]:
print(id(a))

4594498176


In [128]:
print(id(b))

4594498176


In [133]:
#  深复制,但是指向同一个内存区域
# view()
c = a.view()
print(c is a)
a[3] = 4
print('----')
print(a)
print(c)
print('-------')
print(id(a))
print(id(c))

False
----
[0 1 2 4]
[0 1 2 4]
-------
4594315712
4594499136


In [138]:
# 深复制，而且指向了不同的区域
d = c.copy()
print(d is c)
print('-------')
print(d)
print(c)
c[3] = 10

print(c)
print(d)

print(id(c))
print(id(d))

False
-------
[ 0  1  2 10]
[ 0  1  2 10]
[ 0  1  2 10]
[ 0  1  2 10]
4594499136
4594317072


# 索引操作

In [142]:
data = np.sin(np.arange(20).reshape(5,4))
print(data)
print(data.shape)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
(5, 4)


In [141]:
# 按照列查找 元素最大的值的索引
ind = data.argmax(axis=0)
print(ind)
# 根据最大值的索引，查找最大值
data_max = data[ind,range(data.shape[1])]
print(data_max)

[2 0 3 1]
[0.98935825 0.84147098 0.99060736 0.6569866 ]


# tile 函数

In [147]:
a = np.arange(0,40,10)
print(a)
np.tile(a,(2,3))

[ 0 10 20 30]


array([[ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30]])

# sort 函数

In [149]:
a = np.array([3,4,1,2,6,5])
print(a)
np.sort(a)

[3 4 1 2 6 5]


array([1, 2, 3, 4, 5, 6])